[package]
name = "localnative_core"
description = "localnative core lib"
homepage = "https://localnative.app"
authors = ["Yi Wang"]
version = "0.4.2"
license = "AGPL-3.0"
edition = "2018"
[dependencies.rusqlite]
version = "0.20.0"
features = ["bundled"]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.10.2", default-features = false }

[dependencies]
linked_hash_set = "0.1.3"
regex = "1.3.1"
time = "0.1.42"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.44"
dirs = "2.0.2"
base64 = "0.10.1"
rustc-serialize = "0.3.24"
uuid = { version = "0.7.4", features = ["v4"] }
semver = "0.9.0"
tokio = { version = "0.2", features = ["full"] }
tokio-serde = { version = "0.6", features = ["json"] }
futures = "0.3"
tarpc = { version = "0.20.0", features = ["full"]}

[lib]
name = "localnative_core"
# android only need this
# crate-type = ["cdylib"]
# ios works as below
# crate-type = ["staticlib"]
